### PR TITLE
[BD-6] Run tests in python 3.8

### PR DESCRIPTION
**Pull request by morenol**
**Description:** 
Add tests in python 3.8, remove python 3.5 tests and remove python 3.6 tests.
Add classifiers of python 3.5 and python 3.8

## Reviewers
- [ ] @ericfab179
- [ ] @awais786

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @morenol! I've created [OSPR-4478](https://openedx.atlassian.net/browse/OSPR-4478) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by morenol** [comment]
The quality tests in python 3.5 are failing because https://github.com/psf/black does not support python 3.5 ( this is currently using py36)

**Comment by awais786** [comment]
> The quality tests in python 3.5 are failing because https://github.com/psf/black does not support python 3.5 ( this is currently using py36)
> 
> I am not sure what we have to do in this case.

build is green all combinations.

**Comment by morenol** [comment]
> > The quality tests in python 3.5 are failing because https://github.com/psf/black does not support python 3.5 ( this is currently using py36)
> > I am not sure what we have to do in this case.
> 
> build is green all combinations.

Yes, that was due to my last commit, I am not sure if that is OK

**Comment by morenol** [comment]
In fact I think that it is not ok, because it is not running the black command in the python 3.8 version

**Comment by morenol** [comment]
I decided to only run the quality tests in python 3.8, let me know if you think that it is ok @awais786 @mraarif @mzulqarnain1

**Comment by mraarif** [comment]
I assume it's black is the package, I think it should be fine.

**Comment by morenol** [comment]
Master version has python 3.8 tests

**Comment by edx-webhook** [comment]
@morenol Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/scriv&entry.867055334=https://github.com/edx/scriv/pull/4&entry.1484655318=https://github.com/morenol&entry.752974735=2020-05-06+17:31&entry.1917517419=2020-05-25+20:27&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
